# Generated by Django 6.0.7 on 2026-08-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('discount', models.PositiveIntegerField(help_text='Discount in percentage')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
